# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_data',
            name='otp',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
