# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_otp_data_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_data',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
